-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Categories CASCADE;
DROP TABLE IF EXISTS Types CASCADE;
DROP TABLE IF EXISTS Jobs CASCADE;
DROP TABLE IF EXISTS Employer CASCADE;
DROP TABLE IF EXISTS Employee CASCADE;
DROP TABLE IF EXISTS Employee_Jobs_Apply CASCADE;
